// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3ySStmje6PZRDmClZQZJ6FTrt0vIEeiE',
    appId: '1:819752428967:android:bfeb7b2d260270c1610282',
    messagingSenderId: '819752428967',
    projectId: 'authentication-e4eb6',
    authDomain: 'authflutter-e4eb6.firebaseapp.com',
    storageBucket: 'authentication-e4eb6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3ySStmje6PZRDmClZQZJ6FTrt0vIEeiEE',
    appId: '1:819752428967:android:bfeb7b2d260270c1610282',
    messagingSenderId: '819752428967',
    projectId: 'authentication-e4eb6',
    storageBucket: 'authentication-e4eb6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3ySStmje6PZRDmClZQZJ6FTrt0vIEeiE',
    appId: '1:819752428967:android:bfeb7b2d260270c1610282',
    messagingSenderId: '819752428967',
    projectId: 'authentication-e4eb6',
    storageBucket: 'authentication-e4eb6.appspot.com',
    iosBundleId: 'com.example.counter_texth',
  );
}
